AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Resources:

  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri:
        Bucket: !Ref CodeBucket
        Key: !Ref CodeKey
      Handler: !Ref HandlerPath
      Role: !GetAtt
        - LambdaExecutionRole
        - Arn
      Runtime: java8
      Events:
        CreateActivity:
          Type: Api
          Properties:
            Method: POST
            Path: /createactivity
        DescribeActivity:
          Type: Api
          Properties:
            Method: POST
            Path: /describeactivity
        DescribeActivities:
          Type: Api
          Properties:
            Method: POST
            Path: /describeactivities
        UpdateActivity:
          Type: Api
          Properties:
            Method: POST
            Path: /updateactivity
        DeleteActivity:
          Type: Api
          Properties:
            Method: POST
            Path: /deleteactivity
      Timeout: 30
      MemorySize: 384

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'

Parameters:
  CodeBucket:
    Type: String
  CodeKey:
    Type: String
  HandlerPath:
    Type: String
